[build]
  command = """
    go run ./cmd/main.go && \
    cp -r static/* templates/
  """
  publish = "templates"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"