[build]
  command = """
    go run ./cmd/main.go && \
    mkdir -p templates/static && \
    cp -r static/* templates/static/
  """
  publish = "templates"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"